from __future__ import annotations

import logging
import os
import shutil
import pickle
from typing import Any

import lightgbm as lgb
import numpy as np

logger = logging.getLogger(__name__)

class MetaLabeler:
    """
    ML Supervisor layer that predicts the probability of success for a trade signal.
    
    This is a 'Meta-Labeler' (Advancing Labeling technique) that filters signals 
    generated by a base strategy (Kalman Filter).
    """

    def __init__(self, model_path: str | None = None) -> None:
        self.model_path = model_path or "run_state/meta_labeler.lgb"
        self._model = None
        self._is_trained = False
        self._load_model()

    def _load_model(self) -> None:
        if os.path.exists(self.model_path):
            try:
                self._model = lgb.Booster(model_file=self.model_path)
                self._is_trained = True
                logger.info("MetaLabeler: Loaded model from %s", self.model_path)
            except Exception as e:
                logger.error("MetaLabeler: Failed to load model: %s. Quarantining corrupted file.", e)
                try:
                    # Move corrupted model to .bak to allow fresh training
                    shutil.move(self.model_path, self.model_path + ".bak")
                except Exception as move_err:
                    logger.error("MetaLabeler: Failed to quarantine file: %s", move_err)
        else:
            logger.warning("MetaLabeler: Model not found at %s. Running in pass-through mode (Confidence=1.0).", self.model_path)

    def predict_confidence(
        self, 
        kalman_residual: float, 
        bayesian_prob: float, 
        vix_level: float, 
        sector_concentration: float
    ) -> float:
        """
        Returns the probability of success (0.0 to 1.0).
        If no model is loaded, returns 1.0 (optimistic pass-through).
        """
        if not self._is_trained or self._model is None:
            return 1.0

        # Feature vector
        features = np.array([[
            kalman_residual, 
            bayesian_prob, 
            vix_level, 
            sector_concentration
        ]])
        
        try:
            # Predict probability
            prob = self._model.predict(features)[0]
            return float(prob)
        except Exception as e:
            logger.error("MetaLabeler: Prediction error: %s", e)
            return 0.0

    def train(self, X: np.ndarray, y: np.ndarray) -> None:
        """
        Train the LightGBM model on historical signal data.
        X: features [[residual, bayesian, vix, conc], ...]
        y: binary outcome [0, 1] (1 if signal resulted in profit)
        """
        logger.info("MetaLabeler: Training model with %d samples...", len(X))
        
        train_data = lgb.Dataset(X, label=y)
        params = {
            "objective": "binary",
            "metric": "binary_logloss",
            "verbosity": -1,
            "boosting_type": "gbdt",
            "num_leaves": 31,
            "learning_rate": 0.05,
            "feature_fraction": 0.9
        }
        
        self._model = lgb.train(params, train_data, num_boost_round=100)
        self._model.save_model(self.model_path)
        self._is_trained = True
        logger.info("MetaLabeler: Training complete. Saved to %s", self.model_path)
