"""add_trading_state_migration_fields

Revision ID: 94a3c23ab97b
Revises: b2ec69262b3f
Create Date: 2026-02-17 23:35:19.731975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a3c23ab97b'
down_revision: Union[str, None] = 'b2ec69262b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('initial_balance', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('positions', sa.Column('side', sa.String(length=10), nullable=True))
    op.add_column('positions', sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('positions', sa.Column('entry_time', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('direction', sa.String(length=20), nullable=True))
    op.add_column('signals', sa.Column('strength_pct', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'strength_pct')
    op.drop_column('signals', 'direction')
    op.drop_column('positions', 'entry_time')
    op.drop_column('positions', 'pnl_pct')
    op.drop_column('positions', 'side')
    op.drop_column('portfolios', 'initial_balance')
    # ### end Alembic commands ###
