"""Add trading and audit schemas

Revision ID: b2ec69262b3f
Revises: 001
Create Date: 2026-02-17 22:43:46.613657
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ec69262b3f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types first (required for PostgreSQL)
    sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscriptiontier').create(op.get_bind(), checkfirst=True)
    sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus').create(op.get_bind(), checkfirst=True)
    
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'CANCELLED', 'REJECTED', 'FAILED', name='orderstatus'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('triggered_order_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['triggered_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.alter_column('feature_access', 'tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'),
               existing_nullable=False,
               postgresql_using='tier::subscriptiontier')
    op.alter_column('service_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'),
               existing_nullable=False,
               postgresql_using='status::jobstatus')
    op.create_index(op.f('ix_service_jobs_feature_key'), 'service_jobs', ['feature_key'], unique=False)
    op.create_index(op.f('ix_service_jobs_user_id'), 'service_jobs', ['user_id'], unique=False)
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'),
               existing_nullable=False,
               postgresql_using='tier::subscriptiontier')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_service_jobs_user_id'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_feature_key'), table_name='service_jobs')
    op.alter_column('service_jobs', 'status',
               existing_type=sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('feature_access', 'tier',
               existing_type=sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
